### ISSUE TITLE
Add network when already connected to a ssid = save connection even if password is wrong

### ISSUE THREAD

**Issue by slegouffe** [meg768/rpi-wifi-connection#3]
Hi ! 

Here is the situation : My RPi is connected to my "home" wifi, now I want to associate it to my "iphone". If I run .connect() everything is ok, expect that the "waiting for network connection" return immediatly true as I'm previously connected. In this case If I set a wrong password, the new network is saved and the old is set to "disabled=1"...
Suggestion : 
Create to new methods "reconnect" and "disconnect" and in "connect" method  call disconnect at the very beginning and at the very end of "connect" method, if everything is ok add a call to "reconnect" method.

Here what could be the new suggesting methods :

`disconnect() {
        console.log('Disconnecting...');
        return new Promise((resolve, reject) => { 
            this.wpa_cli('disconnect').then((result) => {
                setTimeout(resolve, 500); //--wait to be sure that wlan is really disconnected
            })
            .catch((error) => {
                reject(error);
            })
        });
    }`

`reconnect() {
        console.log('Reconnecting...');
        return new Promise((resolve, reject) => {
            this.wpa_cli('reconnect').then(() => {
                resolve();
            })
            .catch((error) => {
                reject(error);
            })
        });
    }`

Let me know if you are ok with that...

Bye !

**Comment by meg768** [comment]
I see, yes, that is a consequence of the latest change I made... :)

**Comment by meg768** [comment]
Maybe waitForNetworkConnection() should not only check for connection but also check so the connection is to the specified ssid? That would fix the problem, right? I will give it a try to see if that works...

**Comment by meg768** [comment]
Seems to be working now.

**Comment by slegouffe** [comment]
Hello ! 

I'm still in trouble as when I test the new version with a bad ssid/password, the script don't go back to previous configuration so I loose my wifi connection and I'm so sad ! ;-)

**Comment by meg768** [comment]
Can you post the code that fails? After reconfigure() is called in the error handler it takes a second or so until the connection is restored to the working ssid.

**Comment by slegouffe** [comment]
My mistake, it actually works fine ! Just forget to reload my main node script :-/ 

Thks !
