### ISSUE TITLE
Changing console.log to debug print?

### ISSUE THREAD

**Issue by AnderbergE** [meg768/rpi-wifi-connection#6]
Thanks for a very useful library 👍 
I notice a lot of console logs when calling the connect function and I was wondering if that is by design or if it could be moved to a debug log like the rest of the logging?

This would be a suggested solution:
`debug(sprintf('Connection status ssid=%s ip_address=%s ...', status.ssid || '', status.ip_address || ''));`

https://github.com/meg768/rpi-wifi-connection/blob/9af7fcf759eef3f3660a728c0a6b0a34a59c1b3c/src/wifi-connection.js#L211

**Comment by meg768** [comment]
Added your code to version 1.0.17. Thanks, and sorry for the delay...
